spring:
  application:
   name: conference-room-booking
  datasource:
    url: jdbc:h2:mem:bookingDB
    driverClassName: org.h2.Driver
    username: mashreq
    password: mashreq123
  jpa:
      hibernate:
        ddl-auto: update
  h2:
      console:
        enabled: true

server:
  servlet:
    context-path: /api/v1/conference-room-booking

jwt:
  secret: conferenceroombookingeroombooking
